category: crypto
points:   150
short:    shakespear
name:     "Shakespear"
author:   javach
decription: >
  Мы получили странное сообщение из космоса. Похоже на какую-то
  инопланетную поэзию. Сможете расшифровать?
attachments:
  - text.txt
flags:
  -
    text: "ugramadpoetry"