FROM python:alpine

RUN apk add --update --no-cache build-base linux-headers postgresql-dev python3-dev musl-dev && \
    pip3 install uwsgi flask peewee psycopg2 python-telegram-bot && \
    rm -r /root/.cache && \
    apk del build-base linux-headers

    
ENV PYTHONPATH=/app/ 
EXPOSE 8000
COPY config /etc/uwsgi
WORKDIR /app/

CMD ["uwsgi", "--ini", "/etc/uwsgi/uwsgi.ini"]
