category: crypto
points:   200
short:    shakespeare
name:     "Shakespeare"
author:   javach
decription: >
  Мы получили странное сообщение из космоса. Похоже на какую-то
  инопланетную поэзию. Сможете расшифровать?
attachments:
  - text.txt
flags:
  -
    text: "ugramadpoetry"
