category:   forensics
points:     500
short:      yakubovich
name:       "Yakubovich"
author:     vanyaklimenko
description: >
     Секретарь из Югорского НИИ информационных технологий просила передать, что их сфера деятельности глобально расширяется.
url: https://geoportal-uriit.ru/
hints:
  -
    cost: 50
    text: "Якубович тут ни при чём. А фотография Международной космической станции?"
  -
    cost: 200
    text: "... Вы позвонили. Из трубки раздался таинственный голос, представившийся как радиолюбитель Лёня из Москвы. Он стал рассказывать вам что-то совсем невнятное о FM-сигнале с МКС и каком-то медленном телевидении. К чему бы это он?"
flags:
  -
    text:   "ugra_vy_p0zvon1l1"
