version: "3.6"
services:
    web:
        image: sdelrio/docker-minimal-nginx
        volumes:
            - ./private:/usr/share/nginx/html
        command: ["nginx", "-g", "daemon off;"]
        ports:
            - "30001:8080"
        restart: always
