category:   web
points:     200
short:      minesweeper
name:       Minesweeper
author:     javach
description: >
    Говорят, Пётр Пывнер решил заняться бизнесом в Telegram. Начал он с простой
    веб-игры — классического сапёра. Игра лежит тут: @petersweeperbot. Каждому, 
    кто наберёт 200 баллов и больше, Пётр обещает большое вознаграждение. 
    Однако, как вы уже могли догадаться, игры Петра такие же, как и его сайты.
url: https://t.me/petersweeperbot
flags:
  -
    text:   "ugra_html_games_are_not_secure"