version: "3.6"
services:
    bot:
        image: python:alpine
        depends_on:
            - postgres
        volumes:
            - ./private/bot:/app/bot/
            - ./private/common:/app/common/
        environment: 
            PYTHONPATH: /app/
        working_dir: /app/bot/
        command: ["python3", "bot.py"]
        restart: always
    web:
        build:
            context: ./private
            dockerfile: Dockerfile
        ports: "8000:8000"
        image: ugractf/minesweeper-web
        depends_on:
            - postgres
        restart: always
    postgres:
        image: postgres:alpine
        restart: always
