category:   recon
points:     150
short:      food
name:       Арслан любит кушать
author:     arimionimm
description: >
    Вот.
url: https://dailynotes.ugractf.ru/
flags:
  -
    text:   "ugra_ArsLaN_lovs_eAT"
