category:   forensics
points:     100
short:      malware
name:       International malware
author:     nsychev
description: >
    Нашли ещё один файлообменник Петра Пывнера. На этот раз не 
    в скайпе. Найдите флаг.
url: https://yadi.sk/d/kE6vikFs3X5E2J
flags:
  -
    text:   "ugra_it_was_easy.pcap"